name: Workflow Setup
description: "Configure common steps for all workflows"
runs:
  using: "composite"
  steps:
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: 17
        cache: 'gradle'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Accept licenses
      run: yes | sdkmanager --licenses 2>/dev/null
      shell: bash

    - name: Done
      run: echo "Setup complete"
      shell: bash

